export type BodyInterestSlot =
  | 'operationalUse'
  | 'localConflict'
  | 'visualCue'
  | 'settlementStrain'
  | 'surveyQuestion'
  | 'operationalConstraint'

export type BodyInterestGroup =
  | 'rocky'
  | 'heavySolid'
  | 'envelope'
  | 'gasGiant'
  | 'iceGiant'
  | 'belt'
  | 'minorFrontier'
  | 'anomaly'
  | 'humanAltered'

export type BodyInterestPool = Record<BodyInterestSlot, readonly string[]>

export const bodyInterestPools: Record<BodyInterestGroup, BodyInterestPool> = {
  rocky: {
    operationalUse: [
      'automated cargo hops across stable highlands',
      'terminator-route staging and surface relays',
      'shielded boreholes hiding fuel and survey caches',
      'brine-margin sample camps and prospect pits',
      'old terraforming works repurposed as salvage yards',
      'storm-shadow basins with short-cycle extraction crews',
    ],
    localConflict: [
      'claim maps disagreeing over the same workable ground',
      'water rights following buried channels nobody has traced',
      'quarantine law blocking the most valuable sites',
      'beacon stakes moving after each dust season',
      'old survey errors hardening into legal borders',
      'routine claims becoming interdiction cases',
    ],
    visualCue: [
      'glassy ejecta flashing under a low, hard sun',
      'dust trails crossing abandoned pads',
      'distant rigs floating in horizon haze',
      'black basalt plains ringing with sensor static',
      'frost cliffs glowing blue beneath work lights',
      'brine pans mirroring the stars between cracked salt ribs',
    ],
    settlementStrain: [
      'dome space running out before import capacity catches up',
      'sealed farmland demand rising faster than construction',
      'ice haulers deciding which habitats get another season',
      'microbial preserves limiting where foundations can go',
      'cooling rights becoming more valuable than land',
      'radiation shelters setting the real price of expansion',
    ],
    surveyQuestion: [
      'whether subsurface fractures still move usable volatiles',
      'how deep the ancient impact melt really extends',
      'which basins can hold pressure domes through seasonal stress',
      'whether biosignatures are native, imported, or engineered',
      'where the radiation shadow stays stable enough for a depot',
      'why gravity instruments disagree with ordinary geology',
    ],
    operationalConstraint: [
      'fine dust defeating seals faster than crews can replace them',
      'thermal swing limiting every surface shift to narrow windows',
      'corrosive condensate eating exposed intakes',
      'radiation alarms forcing work into brief shadow cycles',
      'brine crust collapsing under heavy crawlers',
      'clean-room protocols slowing movement between protected sites',
    ],
  },
  heavySolid: {
    operationalUse: [
      'pressure-rated foundries near dense mineral uplifts',
      'gravity-assisted test ranges for ruggedized hulls',
      'deep-well gas cracking under armored domes',
      'high-mass cargo lanes tied to reinforced anchors',
      'terraforming pilot basins with strict fail-safes',
      'endurance labs for crews and machines built for heavy gravity',
    ],
    localConflict: [
      'terraforming syndicates overruling habitat engineers',
      'crews contesting hazard pay and descent risk',
      'local factions contesting protected water rights',
      'orbital investors abandoning ground infrastructure',
      'landing guilds rationing descent windows',
      'survey teams hiding subsidence reports',
    ],
    visualCue: [
      'air thick enough to swallow engine noise',
      'horizon haze bending distant pads into amber silhouettes',
      'high-gravity dust dragging at movement',
      'hab struts groaning after each tremor',
      'metallic clouds rolling low over sealed works',
      'landing scars black across basalt flats',
    ],
    settlementStrain: [
      'maintenance costs rising faster than harvest yields',
      'habitat floors buckling under constant load',
      'new arrivals failing gravity adaptation cycles',
      'residents limited to reinforced sections',
      'surface expansion delayed by landing losses',
      'cargo prices strangling independent habitats',
    ],
    surveyQuestion: [
      'whether the atmosphere can be tapped without runaway warming',
      'which descent corridors survive seasonal pressure shifts',
      'how much crustal movement the habitats can tolerate',
      'where gravity stress will break buried transit lines',
      'whether terraforming gains justify evacuation exposure',
      'which seams can fund the next infrastructure cycle',
    ],
    operationalConstraint: [
      'descent fuel margins needing storm abort reserves',
      'pressure seals requiring inspection after every excursion',
      'cargo lifts running only inside narrow launch windows',
      'unadapted personnel facing strict exposure limits',
      'terraforming equipment needing fail-closed behavior',
      'survey drones requiring crush-rated frames and redundant lift',
    ],
  },
  envelope: {
    operationalUse: [
      'aerostat refineries riding stable pressure shelves',
      'orbital intake skimmers sampling upper-envelope volatiles',
      'hycean platform surveys above suspected warm layers',
      'pressure-gradient labs testing deep-atmosphere chemistry',
      'envelope mining routes keyed to circulation bands',
      'fuel depots fed by hydrogen-rich intake streams',
    ],
    localConflict: [
      'competing claims over the safest aerostat band',
      'unlicensed harvesters disrupting long-term survey baselines',
      'local crews divided over hycean-candidate protections',
      'corporate patrols excluding rivals from profitable layers',
      'science teams resisting premature core prospecting',
      'forecasters selling access to transient uplift columns',
    ],
    visualCue: [
      'stacked cloud bands glowing through copper-green haze',
      'deep lightning pulsing below the visible deck',
      'ammonia frost glittering across intake vanes',
      'ocean-color spectra flickering beneath broken high clouds',
      'auroral sheets crawling over the nightside limb',
      'dark storm wells opening inside the envelope',
    ],
    settlementStrain: [
      'stable buoyancy zones forcing dense vertical zoning',
      'uncertain ocean signatures delaying permanent investment',
      'volatile harvest quotas outpacing safety inspections',
      'storm migration compressing crews into orbital refuges',
      'pressure-rated infrastructure slowing every expansion',
      'radiation shelter demand exceeding hardened capacity',
    ],
    surveyQuestion: [
      'whether the water signal marks a true hycean layer',
      'how deep the temperate pressure envelope extends',
      'which cloud bands conceal harvestable organics',
      'whether the rocky core is intact, eroded, or exposed',
      'how often deep storms breach operational altitude limits',
      'which pressure shelves can support long-duration aerostats',
    ],
    operationalConstraint: [
      'crush-depth margins narrower than published models',
      'navigation windows limited by fast-moving shear layers',
      'intake operations stopping during charged storm outbreaks',
      'ballast systems tuned to narrow temperature-pressure bands',
      'probe telemetry degrading below the reflective haze boundary',
      'communications distorted by ionized upper-atmosphere weather',
    ],
  },
  gasGiant: {
    operationalUse: [
      'upper-atmosphere fuel-skimming corridors',
      'deep-well slingshot routes for outer-system traffic',
      'magnetosphere power-tap experiments',
      'ring-plane navigation and debris mapping',
      'moon-to-moon freight consolidation',
      'radiation-hardened transfer hubs',
    ],
    localConflict: [
      'skimmer crews contesting safe dive windows',
      'inner-moon ports rationing shielded berths',
      'ring miners under pressure from navigation authorities',
      'outer moons resisting fuel cartel pricing',
      'military patrols controlling magnetosphere lanes',
      'moon governments disputing transfer-fee rights',
    ],
    visualCue: [
      'banded storms filling half the sky',
      'auroras rippling across the polar crown',
      'static hiss from the radiation belts',
      'ring shadows striping moonlit approaches',
      'charged dust glittering along the ring plane',
      'eclipses moving across the cloud tops',
    ],
    settlementStrain: [
      'shielding demand outpacing local manufacturing',
      'fuel traffic crowding fragile moon ports',
      'radiation exposure limiting labor rotations',
      'ring debris threatening orbital habitats',
      'refinery expansion straining ice reserves',
      'cargo delays cascading through moon markets',
    ],
    surveyQuestion: [
      'which moons anchor the fuel economy',
      'where skimming lanes avoid major storm systems',
      'how far the lethal belts extend',
      'which ring arcs contain useful volatiles',
      'whether minor moons hide stable depots',
      'where magnetosphere flux threatens electronics',
    ],
    operationalConstraint: [
      'tight radiation dose limits near inner moons',
      'narrow skimmer dive windows',
      'high delta-v costs between inclined moons',
      'ring-plane debris hazards',
      'magnetic storms disrupting comms',
      'shielding mass penalties on small craft',
    ],
  },
  iceGiant: {
    operationalUse: [
      'methane and ammonia logistics staging',
      'cold-orbit fuel depots for frontier routes',
      'quiet gravity assists into the far system',
      'outer-moon survey baselines',
      'ring-arc dust and ice sampling',
      'deep-space relay arrays above the pole',
    ],
    localConflict: [
      'outer-moon haulers resisting depot monopolies',
      'science stations blocking refinery expansion',
      'convoy captains fighting over transfer priority',
      'ring shepherd claims disputed by mining crews',
      'fuel brokers manipulating volatile reserves',
      'moon councils taxing every outbound burn',
    ],
    visualCue: [
      'a pale cyan disk hanging in black space',
      'thin rings cutting across the planet glow',
      'dim sunlight on frost-white moons',
      'magnetic auroras far from the rotation pole',
      'ice dust flashing in station lights',
      'cold static in the comms background',
    ],
    settlementStrain: [
      'thin traffic making every shipment political',
      'cryogenic systems failing under long duty cycles',
      'volatile demand exceeding local extraction',
      'small populations dependent on convoy timing',
      'depot capacity limiting exploration range',
      'specialist technicians trapped by distance',
    ],
    surveyQuestion: [
      'which moons can support reliable depots',
      'where ring material offers recoverable ice',
      'how tilted magnetic fields affect routes',
      'which transfer paths minimize rescue exposure',
      'whether cloud-skimming is economically viable',
      'which polar orbits can hold relay coverage',
    ],
    operationalConstraint: [
      'slow transfer cycles between distant moons',
      'limited rescue coverage outside convoy lanes',
      'cryogenic maintenance failures in deep cold',
      'low solar power margins',
      'unreliable comms through magnetic disturbance',
      'strict boiloff control for volatile cargo',
    ],
  },
  belt: {
    operationalUse: [
      'distributed claim markers and rotating beacon nets',
      'ore skiffs working staggered rock families',
      'salvage crews shadowing fresh impact trails',
      'traffic-control buoys threading safe drift lanes',
      'covert caches tucked behind radar-bright rubble',
      'navigation relays buried among decoy fragments',
    ],
    localConflict: [
      'overlapping mining stakes across moving claim lines',
      'salvagers accused of stripping active survey sites',
      'haulers ignoring traffic-control exclusion windows',
      'rival crews spoofing beacon ownership tags',
      'station brokers suppressing fresh assay reports',
      'security patrols chasing transponder ghosts',
    ],
    visualCue: [
      'metal pings against the hull like hard rain',
      'navigation screens crowded with amber collision arcs',
      'dust halos flashing under work lights',
      'slow tumbling shadows crossing every viewport',
      'beacon strobes blinking through broken stone',
      'salvage torches flaring behind drifting plates',
    ],
    settlementStrain: [
      'claim towns stretched thin across scattered anchor rocks',
      'miners demanding tighter patrol coverage',
      'dockmasters rationing safe approach windows',
      'survey crews pushing beyond mapped rescue range',
      'traffic controllers overwhelmed by private beacons',
      'refinery quotas driving riskier extraction shifts',
    ],
    surveyQuestion: [
      'which debris family hides the richest parent-body ore',
      'who altered the oldest claim beacons',
      'where the collision cascade will migrate next',
      'whether wreckage masks a larger cache',
      'which safe lane has drifted out of tolerance',
      'who benefits from false navigation clutter',
    ],
    operationalConstraint: [
      'constant micro-impact risk during exterior work',
      'strict lane clearance windows near active claims',
      'transponder noise from thousands of tagged fragments',
      'line-of-sight breaks behind tumbling rubble',
      'limited rescue coverage outside beacon corridors',
      'shield wear from persistent gravel strikes',
    ],
  },
  minorFrontier: {
    operationalUse: [
      'frozen depots for slow outer-system traffic',
      'fallback caches between brighter routes',
      'survey camps with cheap orbital leases',
      'smuggler handoff points under weak traffic control',
      'cold storage yards for volatile cargo',
      'distant refuges for crews avoiding jurisdiction',
    ],
    localConflict: [
      'overlapping claims around one workable approach',
      'depot operators bribing survey crews for silence',
      'exiles contesting corporate salvage rights',
      'smugglers using old beacon codes',
      'patrol contractors disputing authority',
      'prospectors hiding finds from charter holders',
    ],
    visualCue: [
      'dim sunlight over blue-black ice',
      'frost plumes leaking from buried tanks',
      'brittle regolith crunching under mag boots',
      'beacon static rolling across empty bands',
      'hard shadows from low depot lights',
      'antenna farms rimed with frozen exhaust',
    ],
    settlementStrain: [
      'too little heat for casual habitation',
      'depot debt binding crews past contract terms',
      'exiles rationing power through long dark cycles',
      'prospectors crowding the only shielded volume',
      'claims expanding faster than legal review',
      'refugee habs dependent on one aging reactor',
    ],
    surveyQuestion: [
      'whether old scans missed buried volatiles',
      'who altered the claim telemetry',
      'why beacon logs show extra traffic',
      'what fractured the ice beneath the depot',
      'whether an exile camp found something valuable',
      'how recent the unexplained heat bloom is',
    ],
    operationalConstraint: [
      'limited sunlight and brittle power margins',
      'long rescue windows after equipment failure',
      'unreliable comms behind local terrain',
      'fragile landing pads over unstable ice',
      'fuel rationing controlled by depot owners',
      'navigation hazards from obsolete beacons',
    ],
  },
  anomaly: {
    operationalUse: [
      'interdiction relays shadowing unlicensed burns',
      'GU quarantine markers with shifting clearance codes',
      'black-lab calibration ranges for illegal sensors',
      'artificial substrate anchoring unstable jump math',
      'survey dumps full of erased expedition telemetry',
      'hazard buoy networks with selective blind spots',
    ],
    localConflict: [
      'GU patrols contesting salvage crews over sealed debris',
      'corporate surveyors bribing locals for deleted charts',
      'smugglers using interdiction gaps before recalibration',
      'lab heirs denying ownership of contaminated modules',
      'settlements refusing evacuation from a route hazard cone',
      'rival academics fighting over falsified probe data',
    ],
    visualCue: [
      'starlight shearing across manufactured black facets',
      'comms static repeating clipped GU authorization tones',
      'gravitic pulses arriving before their source signatures',
      'dust plumes bending around invisible service geometry',
      'instrument panels blooming with negative-depth returns',
      'shadow bands crossing from no visible occluder',
    ],
    settlementStrain: [
      'evacuation orders throttling ore traffic through the system',
      'quarantine fees bankrupting dependent habitats',
      'survey rumors pulling claim-jumpers into interdicted lanes',
      'black-lab waste fears freezing new settlement permits',
      'GU inspections delaying every outbound convoy window',
      'navigation anomalies stranding seasonal labor rotations',
    ],
    surveyQuestion: [
      'why GU records omit the first survey team',
      'what keeps rewriting the safe approach vector',
      'whether the substrate is structural or containment',
      'who deleted the expedition archive checksum trail',
      'which readings are physical and which are planted',
      'why probe clocks desynchronize inside the hazard',
    ],
    operationalConstraint: [
      'GU transponders needing visibility inside the cordon',
      'active scans triggering automated interdiction challenges',
      'jump plotting requiring hand verification past the buoy line',
      'contaminated surfaces fouling standard docking seals',
      'artificial terrain rejecting low-orbit mapping assumptions',
      'comms encryption degrading near the substrate boundary',
    ],
  },
  humanAltered: {
    operationalUse: [
      'sealed habitat logistics nodes',
      'derelict corporate extraction annexes',
      'quarantine perimeter command sites',
      'artificial shield maintenance grids',
      'failed terraforming control basins',
      'abandoned transit and docking hubs',
    ],
    localConflict: [
      'rival claims over dormant systems',
      'containment breach fears against salvage pressure',
      'corporate secrecy against public hazard maps',
      'crews bypassing quarantine locks',
      'old security systems enforcing expired orders',
      'hidden experiment records worth killing for',
    ],
    visualCue: [
      'stale air cycling through empty corridors',
      'warning strobes behind cracked pressure glass',
      'chemical frost on service conduits',
      'shield hum felt through hull plating',
      'old alert tones repeating evacuation codes',
      'warm machinery under decades of silence',
    ],
    settlementStrain: [
      'overcrowded habitats seeking expansion',
      'refugees occupying unsafe infrastructure',
      'workers trapped by corporate debt contracts',
      'unauthorized farms stressing closed loops',
      'administrators hiding dwindling reserves',
      'quarantined residents bargaining for passage',
    ],
    surveyQuestion: [
      'who still controls the access keys',
      'what was sealed here and why',
      'which systems remain intentionally powered',
      'where the missing personnel records went',
      'whether the shield protects or imprisons',
      'whether abandonment was staged',
    ],
    operationalConstraint: [
      'quarantine law limiting direct contact',
      'shield interference scrambling long-range scans',
      'legacy locks rejecting modern credentials',
      'unstable life support requiring timed entry',
      'contamination protocols slowing every survey',
      'automated security treating repairs as intrusion',
    ],
  },
}
