import type { FactionBank } from '../index'

export const astronomyBank: FactionBank = {
  stems: [
    'Bonn-Tycho',
    'Stellar Survey Cohort',
    'Calibration',
    'Aperture',
    'Lambda',
    'Pulsar Timing',
    'Long Baseline',
    'Spectral Census',
    'Tau Reticuli',
    'Gamma Ledger',
    'Catalog',
    'Watch-Order',
    'Photometric',
    'Ephemeris',
    'Coronagraph',
    'Heliometric',
  ],
  suffixes: [
    'Trust',
    'Cohort',
    'Bureau',
    'Observatory',
    'Consortium',
    'Authority',
    'Service',
    'Council',
    'Registry',
    'Working Group',
  ],
  seedFactions: [],
  kindByDomain: {
    science: ['research consortium', 'survey trust', 'instrument-time authority'],
    governance: ['observational policy bureau', 'spectrum allocation council'],
    trade: ['calibration-licensing trust', 'pulsar-timing service'],
    espionage: ['signal authentication bureau', 'spectrum-watch service'],
    religion: ['archive-order', 'catalog-keeping society'],
    law: ['standards observatory', 'measurement-court bureau'],
    labor: ['observer roster cohort', 'instrument operations service'],
    'route-weather': ['ephemeris service', 'baseline timing authority'],
  },
}
