import type { FactionBank } from '../index'

export const balancedBank: FactionBank = {
  stems: [
    'Kestrel',
    'Red Vane',
    'Glasshouse',
    'Veyra',
    'Orison',
    'Ninth Ledger',
    'Ash Meridian',
    'Helion',
    'Pale',
    'Sepulcher',
    'Iron Compact',
    'Long Hollow',
    'Tenth Wharf',
    'Granite Reach',
    'Lantern',
    'Kestrel-Locke',
    'Vantage Ledger',
    'Hollow Vane',
    'Cinder Reach',
    'Wraith Channel',
    'Sable Reach',
    'Threshold Gate',
    'Drift Ward',
    'Verge Anchor',
  ],
  suffixes: [
    'Compact',
    'Combine',
    'Concession',
    'Office',
    'Authority',
    'Court',
    'Synod',
    'Communion',
    'Charter',
    'Bureau',
    'Circuit',
    'Guild',
    'Registry',
    'Ward',
    'Concern',
    'Cooperative',
  ],
  seedFactions: [
    {
      name: 'Helion Debt Synod',
      kind: 'banking cartel',
      domains: ['trade', 'labor', 'governance'],
      publicFace: 'a debt-trust court that presents itself as neutral credit infrastructure',
    },
    {
      name: 'Veyra-Locke Concession',
      kind: 'megacorp extraction charter',
      domains: ['trade', 'ecology', 'labor'],
      publicFace: 'a concession office that treats resource law as a private operating system',
    },
    {
      name: 'Orison Route Authority',
      kind: 'gate and route bureaucracy',
      domains: ['trade', 'governance', 'public-life'],
      publicFace: 'a transit authority trusted to publish safe windows and customs schedules',
    },
    {
      name: 'Ash Meridian Navy',
      kind: 'regional naval command',
      domains: ['war', 'governance', 'espionage'],
      publicFace: 'a disciplined route-security fleet with sealed casualty accounting',
    },
    {
      name: 'Glasshouse Biosafety Compact',
      kind: 'medical and quarantine consortium',
      domains: ['ecology', 'science', 'governance'],
      publicFace: 'a biosafety compact that can make quarantine feel like law',
    },
    {
      name: 'Kestrel Free Compact',
      kind: 'independent captain compact',
      domains: ['trade', 'crime', 'migration'],
      publicFace: 'a loose compact of free captains, smugglers, and emergency haulers',
    },
    {
      name: 'Ninth Ledger Office',
      kind: 'Sol-interdiction compliance bureau',
      domains: ['espionage', 'governance', 'religion'],
      publicFace: 'a quiet compliance office that seals records before anyone can ask why',
    },
    {
      name: 'Red Vane Labor Combine',
      kind: 'worker and habitat-repair federation',
      domains: ['labor', 'public-life', 'trade'],
      publicFace: 'a worker federation that controls repair crews, strike funds, and funeral broadcasts',
    },
    {
      name: 'Sepulcher Archive Court',
      kind: 'salvage and first-wave title court',
      domains: ['archaeology', 'law', 'trade'],
      publicFace: 'a salvage court that makes dead charters dangerous again',
    },
    {
      name: 'Pale Choir Communion',
      kind: 'Gardener-warning religious network',
      domains: ['religion', 'public-life', 'disaster'],
      publicFace: 'a warning rite network that treats route disasters as moral evidence',
    },
    {
      name: 'Long Hollow Miners Circuit',
      kind: 'asteroid extraction cooperative',
      domains: ['trade', 'labor', 'ecology'],
      publicFace: 'a haulage cooperative that runs its own scrip and settles claims by seniority list',
    },
    {
      name: 'Tenth Wharf Customs Office',
      kind: 'cargo inspection bureau',
      domains: ['trade', 'governance', 'law'],
      publicFace: 'a customs office that can hold a hull in dock until every manifest reconciles',
    },
    {
      name: 'Granite Reach Water Concession',
      kind: 'life-support utility charter',
      domains: ['ecology', 'governance', 'trade'],
      publicFace: 'a utility charter that meters air and water like any other rationed good',
    },
    {
      name: 'Iron Compact Freight Guild',
      kind: 'bonded hauler guild',
      domains: ['trade', 'labor', 'crime'],
      publicFace: 'a bonded guild that insures cargo against pirates it may also be paying',
    },
    {
      name: 'Lantern Circuit Registry',
      kind: 'route-lighting maintenance registry',
      domains: ['governance', 'labor', 'public-life'],
      publicFace: 'a maintenance registry that keeps the beacons lit and bills every ship that used them',
    },
    {
      name: 'Kestrel-Locke Salvage Concern',
      kind: 'wreck-rights salvage concern',
      domains: ['trade', 'law', 'archaeology'],
      publicFace: 'a salvage concern that treats every drifting hull as an open contract',
    },
    {
      name: 'Vantage Ledger Underwriters',
      kind: 'risk-underwriting combine',
      domains: ['trade', 'governance', 'labor'],
      publicFace: 'an underwriting combine that prices every hazard down to the decimal',
    },
    {
      name: 'Hollow Vane Quarantine Ward',
      kind: 'medical isolation ward authority',
      domains: ['ecology', 'science', 'governance'],
      publicFace: 'an isolation ward that decides who gets to leave a sealed berth alive',
    },
    {
      name: 'Cinder Reach Militia Compact',
      kind: 'settlement defense militia',
      domains: ['war', 'labor', 'public-life'],
      publicFace: 'a militia compact raised from off-shift dockworkers and paid in rationed fuel',
    },
    {
      name: 'Wraith Channel Listening Post',
      kind: 'signals-interception cell',
      domains: ['espionage', 'governance', 'war'],
      publicFace: 'a listening post that logs every transmission and answers to no local court',
    },
    {
      name: 'Sable Reach Burial Guild',
      kind: 'death-rites and remains guild',
      domains: ['religion', 'public-life', 'law'],
      publicFace: 'a burial guild that keeps the only accurate death ledger in the system',
    },
    {
      name: 'Threshold Gate Toll Circuit',
      kind: 'gate-toll collection circuit',
      domains: ['trade', 'governance', 'migration'],
      publicFace: 'a toll circuit that prices passage by manifest weight and political favor',
    },
    {
      name: 'Drift Ward Migrant Bureau',
      kind: 'migrant processing bureau',
      domains: ['migration', 'labor', 'governance'],
      publicFace: 'a processing bureau that decides who is a refugee and who is cargo',
    },
    {
      name: 'Verge Anchor Chapel Synod',
      kind: 'route-blessing chapel synod',
      domains: ['religion', 'trade', 'public-life'],
      publicFace: 'a chapel synod that blesses departures for a fee and keeps the accident count quiet',
    },
  ],
  kindByDomain: {
    trade: ['banking cartel', 'megacorp extraction charter', 'gate and route bureaucracy'],
    labor: ['worker and habitat-repair federation', 'banking cartel'],
    governance: ['gate and route bureaucracy', 'regional naval command', 'medical and quarantine consortium'],
    war: ['regional naval command'],
    ecology: ['megacorp extraction charter', 'medical and quarantine consortium'],
    science: ['medical and quarantine consortium'],
    espionage: ['Sol-interdiction compliance bureau', 'regional naval command'],
    religion: ['Gardener-warning religious network', 'Sol-interdiction compliance bureau'],
    crime: ['independent captain compact'],
    migration: ['independent captain compact'],
    'public-life': ['gate and route bureaucracy', 'worker and habitat-repair federation', 'Gardener-warning religious network'],
    archaeology: ['salvage and first-wave title court'],
    law: ['salvage and first-wave title court'],
    disaster: ['Gardener-warning religious network'],
  },
}
