import type { FactionBank } from '../index'

export const balancedBank: FactionBank = {
  stems: [
    'Kestrel',
    'Red Vane',
    'Glasshouse',
    'Veyra',
    'Orison',
    'Ninth Ledger',
    'Ash Meridian',
    'Helion',
    'Pale',
    'Sepulcher',
    'Iron Compact',
    'Long Hollow',
    'Tenth Wharf',
    'Granite Reach',
    'Lantern',
    'Kestrel-Locke',
  ],
  suffixes: [
    'Compact',
    'Combine',
    'Concession',
    'Office',
    'Authority',
    'Court',
    'Synod',
    'Communion',
    'Charter',
    'Bureau',
  ],
  seedFactions: [
    {
      name: 'Helion Debt Synod',
      kind: 'banking cartel',
      domains: ['trade', 'labor', 'governance'],
      publicFace: 'a debt-trust court that presents itself as neutral credit infrastructure',
    },
    {
      name: 'Veyra-Locke Concession',
      kind: 'megacorp extraction charter',
      domains: ['trade', 'ecology', 'labor'],
      publicFace: 'a concession office that treats resource law as a private operating system',
    },
    {
      name: 'Orison Route Authority',
      kind: 'gate and route bureaucracy',
      domains: ['trade', 'governance', 'public-life'],
      publicFace: 'a transit authority trusted to publish safe windows and customs schedules',
    },
    {
      name: 'Ash Meridian Navy',
      kind: 'regional naval command',
      domains: ['war', 'governance', 'espionage'],
      publicFace: 'a disciplined route-security fleet with sealed casualty accounting',
    },
    {
      name: 'Glasshouse Biosafety Compact',
      kind: 'medical and quarantine consortium',
      domains: ['ecology', 'science', 'governance'],
      publicFace: 'a biosafety compact that can make quarantine feel like law',
    },
    {
      name: 'Kestrel Free Compact',
      kind: 'independent captain compact',
      domains: ['trade', 'crime', 'migration'],
      publicFace: 'a loose compact of free captains, smugglers, and emergency haulers',
    },
    {
      name: 'Ninth Ledger Office',
      kind: 'Sol-interdiction compliance bureau',
      domains: ['espionage', 'governance', 'religion'],
      publicFace: 'a quiet compliance office that seals records before anyone can ask why',
    },
    {
      name: 'Red Vane Labor Combine',
      kind: 'worker and habitat-repair federation',
      domains: ['labor', 'public-life', 'trade'],
      publicFace: 'a worker federation that controls repair crews, strike funds, and funeral broadcasts',
    },
    {
      name: 'Sepulcher Archive Court',
      kind: 'salvage and first-wave title court',
      domains: ['archaeology', 'law', 'trade'],
      publicFace: 'a salvage court that makes dead charters dangerous again',
    },
    {
      name: 'Pale Choir Communion',
      kind: 'Gardener-warning religious network',
      domains: ['religion', 'public-life', 'disaster'],
      publicFace: 'a warning rite network that treats route disasters as moral evidence',
    },
  ],
  kindByDomain: {
    trade: ['banking cartel', 'megacorp extraction charter', 'gate and route bureaucracy'],
    labor: ['worker and habitat-repair federation', 'banking cartel'],
    governance: ['gate and route bureaucracy', 'regional naval command', 'medical and quarantine consortium'],
    war: ['regional naval command'],
    ecology: ['megacorp extraction charter', 'medical and quarantine consortium'],
    science: ['medical and quarantine consortium'],
    espionage: ['Sol-interdiction compliance bureau', 'regional naval command'],
    religion: ['Gardener-warning religious network', 'Sol-interdiction compliance bureau'],
    crime: ['independent captain compact'],
    migration: ['independent captain compact'],
    'public-life': ['gate and route bureaucracy', 'worker and habitat-repair federation', 'Gardener-warning religious network'],
    archaeology: ['salvage and first-wave title court'],
    law: ['salvage and first-wave title court'],
    disaster: ['Gardener-warning religious network'],
  },
}
