import type { FactionBank } from '../index'

export const cinematicBank: FactionBank = {
  stems: [
    'Carrion',
    'Black Comet',
    'Last Ledger',
    'Crown of Dust',
    'Brothers of',
    'Sisters of',
    'Salt Wound',
    'Iron Crown',
    'Vow-Breaker',
    'Pale Saint',
    'Red Wake',
    'Knife-and-Crown',
    'Bone Lantern',
    'Long Knife',
    'Widow Star',
    'Gravewatch',
  ],
  suffixes: [
    'Synod',
    'Run',
    'Cabal',
    'Crown',
    'Compact',
    'Brotherhood',
    'Choir',
    'Wake',
    'Order',
    'Pact',
  ],
  seedFactions: [],
  kindByDomain: {
    war: ['mercenary brotherhood', 'oath-bound naval cabal', 'vendetta order'],
    crime: ['cartel of broken oaths', 'vow-breaker syndicate', 'salt-debt cartel'],
    religion: ['vow-binding cult', 'penitent order', 'last-rites synod'],
    labor: ['debt-bound brotherhood', 'salt-wage compact'],
    governance: ['shadow magistrate', 'witness-court'],
    trade: ['knife-debt cartel', 'salt-broker compact'],
    espionage: ['oath-shadow cell', 'penitent listener cabal'],
    disaster: ['gravewatch order', 'last-rites brotherhood'],
  },
}
